apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  ports:
    - port: 3306
      #target port of vprdb pod
      targetPort: 3306 
      protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP